server:
  port: 8081

spring:
  datasource:
    name: local_db
    url: jdbc:mysql://192.168.56.1:3306/manhattan?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    # druid 连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  session:
    store-type: redis

  redis:
      host: 192.168.0.74
      port: 6379
      password: 123456
      database: 0
      # 数据库连接超时时间，2.x 中类型为Duration，需声明单位
      timeout: 60s
      # 连接池配置，2.x中用jedis或者lettuce配置连接池
      jedis:
        pool:
          # 最大空闲连接数
          max-idle: 500
          # 最小空闲连接数
          min-idle: 50
          # 等待可用连接的最大时间，负数为不限制
          max-wait:  -1s
          # 最大活跃连接数，负数为不限制
          max-active: -1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
      call-setters-on-nulls: true

thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  encoding: UTF-8
  cache: false

# 打印sql
logging:
  level:
     com.gyh.manhattan.dao: debug