server:
  port: 8081

spring:
  datasource:
    name: local_db
    url: jdbc:mysql://localhost:3306/manhattan?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    # druid 连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
      call-setters-on-nulls: true

thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  encoding: UTF-8
  cache: false

# 打印sql
logging:
  level:
     com.com.hms.dataexport.dao: debug